alertmanager:
  ## If false, alertmanager will not be installed
  ##
  enabled: false
prometheus-pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: false
service:
  type: LoadBalancer 
